# 端口
server:
    port: 8080


spring:
    data:
        # redis配置
        redis:
            # Redis数据库索引（默认为0）
            database: 0
            # Redis服务器地址
            host: 127.0.0.1
            # Redis服务器连接端口
            port: 6379
            # Redis服务器连接密码（默认为空）
            password: 123456
            # 连接超时时间（毫秒）
            timeout: 10000ms
            lettuce:
                pool:
                    # 连接池最大连接数
                    max-active: 200
                    # 连接池最大阻塞等待时间（使用负值表示没有限制）
                    max-wait: -1ms
                    # 连接池中的最大空闲连接
                    max-idle: 10
                    # 连接池中的最小空闲连接
                    min-idle: 0
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ef?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
        username: root
        password: 123456

mybatis:
    mapper-locations: classpath:com.niuml.auth_security.mapper/*.xml
    configuration:
        map-underscore-to-camel-case: true

